# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    container_name: MONGO    
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
      - ./mongo_config:/data/configdb
    command: --quiet  
