# Use root/example as user/password credentials
version: '3.9'
services:
  mongo:
    container_name: MONGO
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongo_config:/data/configdb
    command: --quiet
volumes:
  mongo_data: